config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root to: "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    can :manage, :all if user.role == 'admin'
    can :destroy, Post, author: user
    can :destroy, Comment, author: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post
  after_save :update_comments_counter

  # A method that updates the comments counter for a post.
  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'
  after_save :update_likes_counter

  # A method that updates the likes counter for a post.
  def update_likes_counter
    update(likes_counter: likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  after_save :increment_posts_counter

  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }

  def increment_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end

  def update_comments_counter
    update(comments_counter: comments.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::API
  respond_to :json
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApplicationController
  def index
    @post = Post.find(params[:post_id])

    render json: @post.comments
  end

  def create
    current_user = params[:user_id]
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user
    @comment.post_id = params[:post_id]
    @post = Post.find(params[:post_id])
    @comment.save!
    render json: @comment, status: :created
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  def index
    @posts = Post.where(author_id: params[:user_id])
    render json: @posts
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  def index
    users = User.all.order(created_at: :asc)
    render json: users, status: :ok
  end

  def show
    user = User.find(params[:id])
    render json: user, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comment_controller.rb
# app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.new(comment_params)
    if @comment.save
      # Update comments counter for the post
      @post.update_comments_counter
      redirect_to @post, notice: 'Comment created successfully.'
    else
      redirect_to @post, alert: 'Failed to create the comment.'
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    # Update comments counter for the post
    @post.update_comments_counter
    redirect_to @post, notice: 'Comment deleted successfully.'
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:author_id, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comments_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]
    post = Post.find(params[:post_id])
    if @comment.save
      redirect_to user_post_path(current_user.id, post)
    else
      render :new
    end
  end

  def destroy
    Comment.delete(params[:id])
    redirect_to user_post_path(params[:user_id], params[:post_id])
  end

  private

  def comments_params
    params.require(:comment).permit(:text, :post_id)
  end
end

app/controllers/like_contorller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @like = @post.likes.new(author: current_user)

    if @like.save
      @post.update_likes_counter
      redirect_to user_post_path(@post.author, @post), notice: 'Post liked successfully.'
    else
      redirect_to user_post_path(@post.author, @post), alert: 'Failed to like the post.'
    end
  end

  def destroy
    @like = @post.likes.find(params[:id])
    @like.destroy
    @post.update_likes_counter
    redirect_to user_post_path(@post.author, @post), notice: 'Post unliked successfully.'
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/post_controller.rb
# app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    @posts = Post.all
  end

  def show
    @recent_comments = @post.recent_comments
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.build
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to user_posts_path(@user), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments, :likes)
    @post = Post.new
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def destroy
    Post.delete(params[:id])
    redirect_to user_posts_path(params[:user_id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/user_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show
    @recent_posts = @user.recent_posts
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo bio])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:posts).order('created_at DESC')
  end

  def show
    @user = User.includes(posts: :comments).find_by(id: params[:id])
  end
end

app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<div class="comment-form-container">
  <h2 class="comment-form-title">Add a New Comment</h2>

  <%= form_with(model: [@post, Comment.new], url: user_post_comments_path(@post.author, @post), class: "comment-form") do |form| %>
    <div class="form-group">
      <%= form.label :text, "Comment:", class: "form-label" %>
      <%= form.text_area :text, rows: 4, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.submit "Create Comment", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class='user_show_container'> 
  <div class='headline_container'>
    <div class="image_container" style="width: 15rem; height: 15rem;">
      <% if @user.photo %>
        <img src="<%= @user.photo %>" class="" >
      <% else %>
        <p> No image found </p>
      <% end %>
    </div>
    <div class="content_show_container">
      <h1 class="">User Name: <%= @user.name %></h1>  
      <h6 class="">Number of posts: <span><%= @user.posts_counter %></span></h6>
    </div>
  </div>

  <div class="user_posts">
    <h2>Posts</h2>
    <% @user.recent_posts.each do |post| %>
      <div class='posts_list'>
        <h3><%= link_to post.title, user_post_path(@user, post) %></h3>
        <%= post.text %> <br> <br>
        Comments: <%= post.comments_counter %>
        Likes: <%= post.likes_counter %>
      </div>
      <% post.comments.each do |comment| %>
        <div class='posts_list'>
          <h3><%= @user.name %>: <%= comment.text %></h3>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="pagination_container">
<%= link_to "Create Post", new_user_post_path(@user), class: "post_create" %>
    

  </div>
  
</div>

app/views/posts/new.html.erb
<div class="post-form-container">
  <h1 class="post-form-title">New Post</h1>

  <%= form_with(model: @post, url: user_posts_path(@post.author), class: "post-form") do |form| %>
    <div class="form-group">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :text, class: "form-label" %>
      <%= form.text_area :text, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.submit "Create Post", class: "btn btn-primary" %>
    </div>
  <% end %>

  <%= link_to 'Back', user_posts_path(@post.author) %>
</div>

app/views/posts/show.html.erb
<div class="user_posts_details">
  <h2>Post</h2>
  <div class='posts_list'>
    <h3>Title: <%= @post.title %></h3>
    <%= @post.text %>
  </div>

  <div class='posts_list'>
    <p>Comments: <%= @post.comments.count %></p>
    <p>Likes: <%= @post.likes_counter %></p>
  </div>

  <div class='posts_list'>
    <% @post.comments.each do |comment| %>
      <div class='posts_list'>
        <h3><%= comment.author.name %>: <%= comment.text %></h3>
      </div>
      <div class="d-flex justify-content-end">
            <% if can? :destroy, comment %>
              <%= button_to "X", user_post_comment_path(comment.author, comment.post, comment), class: "btn btn-dark center text-light m-2", method: :delete, data: { turbo: false } %>
            <% end %>
            </div>
    <% end %>
  </div>
  <div class="pagination_container">
    <%= link_to 'Add a Comment', new_user_post_comment_path(@post.author, @post), class: 'btn btn-primary' %>
  </div>
</div>

app/views/users/index.html.erb
<!-- Add login and sign-up buttons here -->
<div class="user_buttons">
 <%= link_to "Login", new_user_session_path %>
<%= link_to "Sign Up", new_user_registration_path %>
</div>

<div class='user_wrapper'>
  <% @users.each do |user| %>
    <div class="user_container">
      <div class="image_container", style="width: 15rem; height: 15rem;">
        <% if user.photo %>
          <img src="<%= user.photo %>" class="">
        <% else %>
          <p> No image found </p>
        <% end %>
      </div>
      <div class="content_container">
        <h1 class="">User Name: <%= user.name %></h1>
        <h6 class="">Number of posts: <span><%= user.posts_counter %></span></h6>
        <%= link_to "See details", user_path(user), class: "btn-details" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
 <div  class='user_show_container'> 
   <div class='headline_container'>
   <div class="image_container", style="width: 15rem; heigth: 15rem;">
      <% if @user.photo %>
        <img src="<%= @user.photo %>" class="" >
      <% else %>
          <p> No image found </p>
      <% end %>
     </div>
     <div class="content_show_container">
      <h1 class="">User Name: <%= @user.name %></h1>  
        <h6 class="">Number of posts: <span><%= @user.posts_counter %></span></h6>
     </div>
   </div>
   <div class="user_bio">
   <h2>Bio</h2>
   <p><%= @user.bio %></p>   
   </div>
    <div class="user_posts">
    <h2>Posts</h2>
   
   <% @user.recent_posts.each  do |post| %>
     <div class='posts_list'>
    <h3>Title:<%= post.title %></h3>
     <%= post.text %>
      </div>
    <% end %>
    <div class="user_show_button">
        <%= link_to 'See all posts', user_posts_path(@user), class: "btn_show_posts"%>
   </div>

 </div>

</div>

app/views/users/user.html.erb
<h1>User Profile</h1>
<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>
<p>Total Posts: <%= @user.posts.count %></p>

<h2>Recent Posts</h2>
<ul>
  <% @user.recent_posts.each do |post| %>
    <li><%= post.title %> - <%= post.created_at %></li>
  <% end %>
</ul>